In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head().T

,0,1,2,3,4
budget,237000000,300000000,245000000,250000000,260000000
genres,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
homepage,http://www.avatarmovie.com/,http://disney.go.com/disneypictures/pirates/,http://www.sonypictures.com/movies/spectre/,http://www.thedarkknightrises.com/,http://movies.disney.com/john-carter
id,19995,285,206647,49026,49529
keywords,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."
original_language,en,en,en,en,en
original_title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter
overview,"In the 22nd century, a paraplegic Marine is di...","Captain Barbossa, long believed to be dead, ha...",A cryptic message from Bondâ€™s past sends him o...,Following the death of District Attorney Harve...,"John Carter is a war-weary, former military ca..."
popularity,150.437577,139.082615,107.376788,112.31295,43.926995
production_companies,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]"
production_countries,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""US"", ""name"": ""United States o..."
release_date,2009-12-10,2007-05-19,2015-10-26,2012-07-16,2012-03-07
revenue,2787965087,961000000,880674609,1084939099,284139100
runtime,162.0,169.0,148.0,165.0,132.0
spoken_languages,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""iso_639_1"": ""en"", ""name"": ""English""}]"
status,Released,Released,Released,Released,Released
tagline,Enter the World of Pandora.,"At the end of the world, the adventure begins.",A Plan No One Escapes,The Legend Ends,"Lost in our world, found in another."
title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter
vote_average,7.2,6.9,6.3,7.6,6.1
vote_count,11800,4500,4466,9106,2124

In [4]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [6]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

Features Selection

In [7]:
movies= movies[['id', 'title', 'genres', 'overview']]

In [10]:
movies['tags']= movies['overview']+movies['genres']

In [11]:
movies

,id,title,genres,overview,tags
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...
4798,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi just wants to play his guitar and ...,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,[],When ambitious New York attorney Sam is sent t...,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]",Ever since the second grade when he first saw ...,Ever since the second grade when he first saw ...

In [13]:
new_data= movies.drop(columns=['genres','overview'])

In [14]:
new_data

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer(max_features=4803, stop_words='english')

In [19]:
vector= cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [21]:
vector.shape

(4803, 4803)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
similarity= cosine_similarity(vector)

In [24]:
similarity

array([[1.        , 0.56195149, 0.43259046, ..., 0.32963426, 0.        ,
        0.10814761],
       [0.56195149, 1.        , 0.41697519, ..., 0.31773542, 0.        ,
        0.09622504],
       [0.43259046, 0.41697519, 1.        , ..., 0.27516694, 0.        ,
        0.08333333],
       ...,
       [0.32963426, 0.31773542, 0.27516694, ..., 1.        , 0.06263608,
        0.10583344],
       [0.        , 0.        , 0.        , ..., 0.06263608, 1.        ,
        0.05479966],
       [0.10814761, 0.09622504, 0.08333333, ..., 0.10583344, 0.05479966,
        1.        ]])

In [31]:
new_data[new_data['title']=="John Carter"].index[0]

4

In [38]:
distance= sorted(list(enumerate(similarity[4])), reverse=True, key=lambda vector:vector[1])

for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

John Carter
Star Trek: Insurrection
The Fifth Element
The Helix... Loaded
Transformers: Revenge of the Fallen

In [47]:
def recommend(movies):
    index= new_data[new_data['title']==movies].index[0]
    distance= sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [48]:
recommend('Iron Man')

Iron Man
The Helix... Loaded
Godzilla 2000
Iron Man 3
Mad Max Beyond Thunderdome

In [43]:
import pickle

In [45]:
# pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [46]:
# pickle.dump(similarity, open('similarity.pkl', 'wb'))